### ISSUE TITLE
Error while decrypting the excel file (String could not be parsed as XML)

### ISSUE THREAD

**Issue by Portal2Commander** [jaydadhania08/PHPDecryptXLSXWithPassword#1]
First of all thank you for that wonderful library.

I tried the example and get an error:
"String could not be parsed as XML"

The error occurs in line 30 inside PHPDecryptXLSXWithPassword.php:
     `$xml =  new SimpleXMLElement($xmlstr);`

What can I do to debug this error?
Is this error known?

Thank you in advance!

**Comment by jaydadhania08** [comment]
Did you try with the `encrypted.xlsx` file provided in this repo?

If not, here are some steps to debug:
- Make sure it is an XLSX (and not XLS) file, protected with a password
- Create a new XLSX file, add password to it and save - then use that file with this code and see how it goes

If you can send me the file, I can try to debug this issue and see where it goes wrong.

**Comment by jaydadhania08** [comment]
@Portal2Commander Any updates?
[Edit 2021-07-22] Closing the issue for inactivity, feel free to reopen it.
