### ISSUE TITLE
error when reading decrypted xlsx file

### ISSUE THREAD

**Issue by sonicwong** [jaydadhania08/PHPDecryptXLSXWithPassword#2]
I am using php 5.5 with PHPExcel to read the decrypted xlsx file, it show below error:

Fatal error: Call to a member function attributes() on null in /var/www/admin/application/libraries/PHPExcel/Reader/Excel2007.php on line 368
A PHP Error was encountered
Severity: Error

Message: Call to a member function attributes() on null
Filename: Reader/Excel2007.php
Line Number: 368

I use libreoffice to load "decrypted xlsx" and save as other .xlsx file.
PHPExcel can load file without error.

**Comment by jaydadhania08** [comment]
@sonicwong PHPExcel was officially deprecated in 2017, and has not been maintained in years. Please use its direct successor [PHPSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet) and see if the issue still occurs.
