### ISSUE TITLE
Error when changing PHP version

### ISSUE THREAD

**Issue by medbase** [jaydadhania08/PHPDecryptXLSXWithPassword#3]
Hi,

I tried this code in a project on Apache 2 with PHP 7.2.34 and it worked great.

I tried the same code on another sever running Apache2 with  php 7.4.18 and i am getting the following errors when I run the decrypt function

Notice: Only variables should be passed by reference in /usr/share/php/OLE.php on line 244

Notice: Undefined offset: 4294967294 in /usr/share/php/OLE/ChainedBlockStream.php on line 125

Notice: Undefined index: in /usr/share/php/OLE/ChainedBlockStream.php on line 125

Any suggestions?

**Comment by jaydadhania08** [comment]
@medbase Possible steps to debug this:

1. Create a fresh blank XLSX file with password in Excel, use it with PHP 7.4.18 to see if it works.
2. Using `var_dump()` with local variables may be of help comparing actual vs expected value.

I can try to find out why this is happening, could you please share the XLSX file and the associated PHP code block?

**Comment by medbase** [comment]
I was able to solve this issue by manually installing PEAR OLE version 
1.0.0RC8

It was using 1.0.0RC3 as part of the default install.

All is well now.

Thank you

On 2022-06-04 8:41 am, jaydadhania08 wrote:

> @medbase [1] Possible steps to debug this:
> 
> * Create a fresh blank XLSX file with password in Excel, use it with 
> PHP 7.4.18 to see if it works.
> * Using var_dump() with local variables may be of help comparing actual 
> vs expected value.
> 
> I can try to find out why this is happening, could you please share the 
> XLSX file and the associated PHP code block?
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/medbase
[2] 
https://github.com/jaydadhania08/PHPDecryptXLSXWithPassword/issues/3#issuecomment-1146601864
[3]
